language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
# Exclude for django incompatibility
matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_VERSION=2.0
  - python: "2.7"
    env: DJANGO_VERSION=2.1
  - python: "3.4"
    env: DJANGO_VERSION=2.1
  include:
  - python: "3.7"
    env: DJANGO_VERSION=1.11
    dist: xenial
    sudo: required
  - python: "3.7"
    env: DJANGO_VERSION=2.0
    dist: xenial
    sudo: required
  - python: "3.7"
    env: DJANGO_VERSION=2.1
    dist: xenial
    sudo: required
# command to install dependencies
install:
  - pip freeze | xargs pip uninstall -y
  - pip install Django==$DJANGO_VERSION
  - pip install -r requirements/test.txt
# command to run tests
script:
  - pytest --cov . --cov-report xml --junitxml results.xml
after_success:
  - coveralls
